language: cpp
cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/cmake
addons:
  apt:
    packages:
      - gcc-6
      - g++-6
      - qt5-default
    sources: &sources
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:canonical-qt5-edgers/ubuntu1204-qt5'
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux"  ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6; fi
install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p "${DEPS_DIR}" && cd "${DEPS_DIR}"
  # Install a recent CMake
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      # if [[ -z "${DEPS_DIR}/cmake/bin" ]]; then
        CMAKE_URL="https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz"
        mkdir -p cmake && travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" | tar --strip-components=1 -xz -C cmake
      # fi
      export PATH="${DEPS_DIR}/cmake/bin:${PATH}"
    else
      if ! brew ls --version cmake &>/dev/null; then brew install cmake; fi
    fi
    cmake --version
before_script:
  - cd "${TRAVIS_BUILD_DIR}"
  - ./scripts/build.sh
script: ./scripts/tests.sh
